In [1]:
import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
print(df.shape)
print(df.head())

(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [4]:
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [5]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df = df.drop(columns=["Cabin", "PassengerId", "Name", "Ticket"])
df = pd.get_dummies(
    df,
    columns = ["Sex", "Embarked"],
    dtype = int
)
print(df.shape)
print(df.head())

(891, 11)
   Survived  Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male  \
0         0       3  22.0      1      0   7.2500           0         1
1         1       1  38.0      1      0  71.2833           1         0
2         1       3  26.0      0      0   7.9250           1         0
3         1       1  35.0      1      0  53.1000           1         0
4         0       3  35.0      0      0   8.0500           0         1

   Embarked_C  Embarked_Q  Embarked_S
0           0           0           1
1           1           0           0
2           0           0           1
3           0           0           1
4           0           0           1

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop("Survived", axis = 1)
y = df["Survived"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size = 0.2,
    random_state = 42,
    stratify = y
)
print("Features shape:", X.shape)
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Features shape: (891, 10)
Training data shape: (712, 10)
Testing data shape: (179, 10)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("\nClassification Report:")
print(classification_report(y_test,y_pred_lr))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,y_pred_lr))

Logistic Regression Accuracy: 0.8044692737430168

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       110
           1       0.79      0.67      0.72        69

    accuracy                           0.80       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.80      0.80      0.80       179


Confusion Matrix:
[[98 12]
 [23 46]]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
dt_model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7653631284916201

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.88      0.82       110
           1       0.75      0.58      0.66        69

    accuracy                           0.77       179
   macro avg       0.76      0.73      0.74       179
weighted avg       0.76      0.77      0.76       179


Confusion Matrix:
[[97 13]
 [29 40]]

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 0.8212290502793296

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       110
           1       0.81      0.70      0.75        69

    accuracy                           0.82       179
   macro avg       0.82      0.80      0.81       179
weighted avg       0.82      0.82      0.82       179


Confusion Matrix:
[[99 11]
 [21 48]]

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

y_pred_knn = knn_model.predict(X_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_knn))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))

KNN Accuracy: 0.8212290502793296

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.90      0.86       110
           1       0.81      0.70      0.75        69

    accuracy                           0.82       179
   macro avg       0.82      0.80      0.81       179
weighted avg       0.82      0.82      0.82       179


Confusion Matrix:
[[99 11]
 [21 48]]

In [13]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": y_pred_lr,
    "Decision Tree": y_pred_rf,
    "KNN": y_pred_knn
}
results = []
for name, predictions in models.items():
    results.append({
        "Model": name,
        "Accuracy": 
        accuracy_score(y_test, predictions),
        "Precision":
        precision_score(y_test, predictions),
        "Recall":
        recall_score(y_test, predictions),
        "F1-Score": 
        f1_score(y_test, predictions)
    })

    comparison_df = pd.DataFrame(results)
    display(comparison_df.round(3))

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724
1        Decision Tree     0.821      0.814   0.696     0.750

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724
1        Decision Tree     0.821      0.814   0.696     0.750
2                  KNN     0.821      0.814   0.696     0.750

In [15]:
models = {
    "Logistic Regression": y_pred_lr,
    "Decision Tree": y_pred_dt,
    "Random Forest": y_pred_rf, 
    "KNN": y_pred_knn
}
results = []
for name, predictions in models.items():
    results.append({
        "Model": name,
        "Accuracy": 
        accuracy_score(y_test, predictions),
        "Precision":
        precision_score(y_test, predictions, zero_division=0),
        "Recall":
        recall_score(y_test, predictions, zero_division=0),
        "F1-Score":
        f1_score(y_test, predictions, zero_division=0)
    
    })

    comparison_df = pd.DataFrame(results)
    display(comparison_df.round(3))

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724
1        Decision Tree     0.765      0.755   0.580     0.656

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724
1        Decision Tree     0.765      0.755   0.580     0.656
2        Random Forest     0.821      0.814   0.696     0.750

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression     0.804      0.793   0.667     0.724
1        Decision Tree     0.765      0.755   0.580     0.656
2        Random Forest     0.821      0.814   0.696     0.750
3                  KNN     0.821      0.814   0.696     0.750

In [2]:
import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
print(df.shape)
print(df.columns.tolist())

(891, 12)
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
reg_df = pd.read_csv("Titanic-Dataset.csv")
reg_df = reg_df[["Age", "Pclass", "SibSp", "Parch", "Fare"]]

reg_df["Age"] = reg_df["Age"].fillna(reg_df["Age"].median())
reg_df = reg_df.dropna()

print("Missing values:")
print(reg_df.isnull().sum())

Missing values:
Age       0
Pclass    0
SibSp     0
Parch     0
Fare      0
dtype: int64

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load and clean data
reg_df = pd.read_csv("Titanic-Dataset.csv")

reg_df = reg_df[["Age", "Pclass", "SibSp", "Parch", "Fare"]].copy()

for col in reg_df.columns:
    reg_df[col] = pd.to_numeric(reg_df[col], errors="coerce")

reg_df["Age"] = reg_df["Age"].fillna(reg_df["Age"].median())
reg_df = reg_df.dropna()

# Separate features and target
X_reg = reg_df[["Age", "Pclass", "SibSp", "Parch"]]
y_reg = reg_df["Fare"]

# Split data
Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Train model
reg_model = LinearRegression()
reg_model.fit(Xr_train, yr_train)

# Predict and evaluate
fare_pred = reg_model.predict(Xr_test)

print("Missing values:", reg_df.isnull().sum().sum())
print("Training shape:", Xr_train.shape)
print("Testing shape:", Xr_test.shape)
print("MAE:", mean_absolute_error(yr_test, fare_pred))
print("MSE:", mean_squared_error(yr_test, fare_pred))
print("R2 Score:", r2_score(yr_test, fare_pred))

Missing values: 0
Training shape: (712, 4)
Testing shape: (179, 4)
MAE: 19.78196909043905
MSE: 946.3355043476646
R2 Score: 0.3884468201561929

## Conclusion

In this project, supervised machine learning models were implemented using the Titanic dataset. Logistic Regression, Decision Tree, Random Forest, and K-Nearest Neighbors (KNN) were trained to predict passenger survival. Their performance was evaluated using accuracy, precision, recall, and F1-score. Random Forest and KNN achieved approximately 82.1% accuracy in the recorded results. Linear Regression was also implemented separately to predict passenger fare, achieving an R² score of approximately 0.388. This project provided practical experience in data preprocessing, model training, prediction, and performance evaluation using Scikit-learn.